export default {
  id: 'grange-house', version: 1, schemaVersion: 1,
  title: 'Grange House', subtitle: 'A burglary that does not add up',
  setting: 'A private estate outside London · present day', duration: '15–30 min', difficulty: 'A good first case',
  source: { title: 'The Adventure of the Abbey Grange', author: 'Arthur Conan Doyle', url: 'https://www.gutenberg.org/ebooks/108' },
  briefing: 'Elliot Vale was found dead in the dining room of Grange House. His widow, Mara, says three burglars tied her to a chair, killed Elliot, and escaped with silverware. Her aide supports the account. A preliminary scene review raises questions. Establish who caused Elliot’s death and how the scene was staged. Your partner can examine records and follow leads, but the deduction is yours.',
  openingFacts: ['The likely weapon was a bloodied fireplace tool.', 'Mara reported three intruders. Tessa initially corroborates her account.', 'The emergency call was made at 23:18.'],
  characters: [
    { id: 'detective', name: 'Detective Rowan', role: 'Your investigative partner', voice: 'charles', initials: 'DR', initial: true, bio: 'A measured investigator. Ask Rowan to check a lead, compare evidence, or help you get unstuck.', facts: ['You know only the briefing, evidence discovered by the player, and verified investigation results. Offer a direction, never guess the solution.'], topics: ['Check the scene', 'Follow a lead', 'What are we missing?'] },
    { id: 'mara', name: 'Mara Vale', role: 'The widow', voice: 'anna', initials: 'MV', initial: true, bio: 'Elliot’s wife. Composed, exhausted, and protective of her privacy.', facts: ['Your initial account: three strangers entered through the terrace, bound you before the attack, killed Elliot, and stole silverware.', 'You say the intruders drank from three glasses.', 'You raised the alarm at 23:18. Do not add descriptions, motives, or facts not supplied.'], topics: ['The intruders', 'The chair and cord', 'Your marriage'] },
    { id: 'tessa', name: 'Tessa Wright', role: 'The longtime aide', voice: 'alba', initials: 'TW', initial: true, bio: 'Loyal to Mara. Her account closely follows the widow’s.', facts: ['Your initial account: you arrived only after Mara called for help.', 'You support Mara’s account of a burglary but do not claim you witnessed the fatal blow.', 'You are worried about Mara. Do not invent details of the intruders.'], topics: ['When you arrived', 'What you saw', 'Mara’s account'] },
    { id: 'owen', name: 'Owen Pike', role: 'Estate security', voice: 'leo', initials: 'OP', initial: true, bio: 'Responsible for the gate and cameras. Defensive about his shift.', facts: ['You were assigned to the security console that night.', 'The terrace is outside camera coverage. The service gate is recorded.', 'You initially insist you stayed at the console. You did not see the dining-room fight and cannot identify a killer.'], topics: ['Camera coverage', 'Your shift', 'The service gate'] },
    { id: 'jack', name: 'Jack Hale', role: 'A visitor of interest', voice: 'rory', initials: 'JH', initial: false, bio: 'A maritime officer with an old connection to Mara.', facts: ['You know Mara from years ago. Initially you deny visiting that night.', 'You have a fresh forearm injury. Do not invent an explanation beyond the permitted case context.'], topics: ['The recorded visit', 'Your injury', 'The silverware'] }
  ],
  clues: [
    { id: 'E1', title: 'The third wine glass', kind: 'physical', source: 'Scene photograph & existing residue note', body: 'Three glasses sit on the dining table. Two have wine residue and lip marks. The third has residue but no sign anyone drank from it. It weakens the claim that three intruders stopped to drink; it is not proof on its own.', characters: ['mara', 'tessa'], inspectable: true, requires: {} },
    { id: 'E2', title: 'Bound after the attack', kind: 'physical', source: 'Preliminary scene report', body: 'Blood is present on the chair beneath the binding cord. The pattern indicates Mara was placed and tied there after the fatal injury. The curtain cord was cut and deliberately frayed. Her account of being tied before the attack does not fit.', characters: ['mara', 'tessa', 'jack'], inspectable: true, requires: {} },
    { id: 'E3', title: 'Silverware in the pond', kind: 'physical', source: 'Rowan’s grounds search', body: 'The missing silver pieces were hidden in the estate pond. A theft that never left the grounds supports a staged burglary rather than the reported escape.', characters: ['mara', 'tessa', 'jack'] },
    { id: 'E4', title: 'Jack’s recorded visit', kind: 'record', source: 'Service-gate recording & vehicle records', body: 'A single vehicle entered at 22:32 and left at 23:12, before the 23:18 alarm. Existing vehicle records identify the driver as Jack Hale. The records establish presence, not the fatal blow.', characters: ['owen', 'jack'], unlockCharacters: ['jack'] },
    { id: 'E5', title: 'A borrowed burglar story', kind: 'record', source: 'News archive & verified custody records', body: 'Mara’s description closely matches a recently reported burglary group. All three were already in custody that night. The account cannot identify the real visitors.', characters: ['mara', 'tessa'] },
    { id: 'E6', title: 'A fresh forearm injury', kind: 'observation', source: 'Interview observation', body: 'Jack has a fresh bruised forearm. The injury is consistent with a recent struggle, but cannot establish where it happened or who caused the death.', characters: ['jack'], inspectable: true, requires: { characters: ['jack'] } },
    { id: 'E7', title: 'An old connection', kind: 'testimony', source: 'Tessa’s interview', body: 'Tessa says Jack and Mara knew each other years earlier. It explains a possible visit and why the household might protect him; it is context rather than proof.', characters: ['tessa', 'mara', 'jack'], unlockCharacters: ['jack'] },
    { id: 'E8', title: 'Tessa corrects her timeline', kind: 'testimony', source: 'Tessa’s corrected account', body: 'Tessa admits entering immediately after the impact. She saw Jack holding the bloodied fireplace tool beside Elliot. She did not see the strike itself. The account needs corroboration from the independent scene and arrival evidence.', characters: ['tessa', 'jack', 'mara'], unlockCharacters: ['jack'] },
    { id: 'E9', title: 'A lapse at the console', kind: 'testimony', source: 'Owen’s interview', body: 'Owen admits leaving the console on a personal break. Recording continued automatically. His lie protects his job; it does not place him in the dining room.', characters: ['owen'] },
    { id: 'E10', title: 'Jack admits the visit', kind: 'testimony', source: 'Jack’s interview', body: 'Confronted with the gate record, Jack admits visiting Mara privately. He still denies causing Elliot’s death.', characters: ['jack', 'mara'] },
    { id: 'E11', title: 'A concealed violent marriage', kind: 'testimony', source: 'Mara’s interview', body: 'Mara describes Elliot’s violence toward her. It explains the witnesses’ fear and protective behavior. It does not establish who delivered the fatal blow.', characters: ['mara', 'tessa', 'jack'] },
    { id: 'CONFESSION', title: 'A verified account of the fatal blow', kind: 'confession', source: 'Jack’s earned account', body: 'After confrontation with the staging, arrival, and aftermath evidence, Jack admits striking Elliot during the struggle. He gives a held-back detail: he used two half-hitches on the cord tail beneath the chair, matching the private scene note. The case engine verifies that detail.', characters: ['jack'] }
  ],
  reveals: [
    { id: 'owen-break', characterId: 'owen', level: 'partial', topic: 'Press about the security shift, being away from the console, or missing the visitor.', requires: {}, speech: 'I left the console for a personal break. I should have told you. The service-gate camera kept recording, so ask Rowan to check it.', clueIds: ['E9'] },
    { id: 'tessa-connection', characterId: 'tessa', level: 'partial', topic: 'Ask about who Mara knew, a private visitor, or who she might be protecting.', requires: { any: ['E2', 'E3', 'E5'] }, speech: 'Mara knew Jack Hale years ago. If you want to understand who could have visited, you need to speak to him.', clueIds: ['E7'] },
    { id: 'tessa-timeline', characterId: 'tessa', level: 'full', topic: 'Confront the false burglary, your entry time, or what you actually saw after the impact.', requires: { any: ['E2', 'E3'] }, speech: 'I entered just after the impact, earlier than I said. Jack was holding the bloodied fireplace tool beside Elliot. I did not see him strike. We then helped stage the burglary.', clueIds: ['E8'] },
    { id: 'mara-marriage', characterId: 'mara', level: 'partial', topic: 'Ask carefully about the marriage, abuse, fear, or why she protected the visitor.', requires: {}, speech: 'Elliot was violent toward me. I was frightened of him and frightened of what would happen afterward. Please understand that before judging my account.', clueIds: ['E11'] },
    { id: 'mara-staging', characterId: 'mara', level: 'full', topic: 'Confront the chair, glass, silverware, or impossibility of the intruder account.', requires: { any: ['E2', 'E3', 'E5'] }, speech: 'The burglary account was false. I was tied afterward, and we arranged the room to make it look like strangers had been there. I was trying to protect someone.', clueIds: [] },
    { id: 'jack-visit', characterId: 'jack', level: 'partial', topic: 'Confront your presence or recorded vehicle at the estate.', requires: { all: ['E4'] }, speech: 'Yes, I came to see Mara that night. I left before the alarm. I should not have denied the visit, but being there does not tell you everything that happened.', clueIds: ['E10'] },
    { id: 'jack-confession', characterId: 'jack', level: 'full', topic: 'Reconstruct the fight and staging, confront Tessa’s account, and ask for the truth about the fatal blow.', requires: { all: ['E4', 'E8'], any: ['E2', 'E3'] }, speech: 'Elliot hit Mara with his cane and fought me. I struck him with the fireplace tool. We staged the burglary afterward; I tied two half-hitches on the cord tail beneath the chair. That is the full account.', clueIds: ['CONFESSION'], confession: true }
  ],
  leads: [
    { id: 'gate', title: 'Check the service-gate records', description: 'Establish who entered and left before the alarm.', requires: {}, speech: 'The service gate recorded one vehicle arriving at 22:32 and leaving at 23:12. Existing records identify Jack Hale as the driver, so he is now available to interview.', clueIds: ['E4'] },
    { id: 'grounds', title: 'Search for the missing silverware', description: 'Test whether the reported theft left the estate.', requires: { any: ['E1', 'E2'] }, speech: 'The missing silverware was hidden in the estate pond. That supports a staged theft rather than the escape Mara described.', clueIds: ['E3'] },
    { id: 'burglars', title: 'Verify the reported burglar group', description: 'Check the familiar description against independent records.', requires: {}, speech: 'The described burglary group was in custody that night. The witness account appears borrowed from a news report, rather than a reliable description of visitors.', clueIds: ['E5'] }
  ],
  resolution: { culpritId: 'jack', proofGroups: [['E2', 'E3'], ['E4'], ['E8']], confessionId: 'CONFESSION', reconstruction: 'Jack Hale caused Elliot Vale’s death during a violent confrontation. Mara and Tessa helped disguise the incident as a three-person burglary: Mara was bound afterward, the third glass was staged, and the silverware was hidden on the grounds. The scene evidence, gate record, and Tessa’s immediate-aftermath account form a persuasive chain. Establishing these facts does not decide Jack’s legal liability.' }
};
